---
title: "Recipe to prepare data for models"
format: html
editor: source
---

```{r}
library(here)
library(tidyverse)
library(tidymodels)
library(bundle)
```

```{r}
raw_data_dir <- here("data")
prepped_data_dir <- here("data-prepped")
```

## Open up the data

```{r}
train_data <- readRDS(file=here(prepped_data_dir, 'train_split.rds'))

df_train <- train_data$df_train
folds <- train_data$folds
```


## Create recipe object

See <https://recipes.tidymodels.org/articles/recipes.html>

```{r}
rec <- recipe(new_child ~ ., data=df_train) %>%
  # the ID variables are not a predictor
  update_role(nomem_encr, nohouse_encr, new_role = "ID") %>%
  # this is also NOT a predictor
  update_role(any_new_child_in_hh, new_role = "splitting indicator") %>%
  # use k nearest neighbors to impute missing predictors
  step_impute_knn(all_predictors()) %>%
  # convert new_child to factor
  #step_num2factor(new_child,
  #                levels=paste(0:1)) %>%
  # convert gender to a factor
  step_num2factor(gender_bg,
                  levels=c("m", "f")) %>%
  #step_num2factor(contains('woonvorm'),
  #                levels=paste(1:5)) %>%
  #step_num2factor(contains('partner'),
  #                levels=paste(0:1)) %>%
  # turn all categorical predictors into dummies
  step_dummy(all_nominal_predictors()) %>%
  # center + scale most numeric predictors
  # EXCEPT
  step_center(all_numeric_predictors(), -contains('birthyear_bg')) %>%
  step_scale(all_numeric_predictors(), -contains('birthyear_bg')) %>%
  # center + scale all numeric predictors
  #step_center(all_numeric_predictors()) %>%
  #step_scale(all_numeric_predictors())
  # remove zero variance predictors
  step_zv(all_predictors())
 
rec
```

```{r}
saveRDS(bundle(rec),
        file=here(prepped_data_dir, 'recipe.rds'))
```

